-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 08, 2024 at 02:07 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `roxiler`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `product_id` bigint(20) NOT NULL,
  `product_category` text NOT NULL,
  `product_title` text NOT NULL,
  `product_description` text NOT NULL,
  `product_image` text NOT NULL,
  `product_price` float NOT NULL,
  `product_sold` varchar(10) NOT NULL,
  `product_date_of_sale` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_category`, `product_title`, `product_description`, `product_image`, `product_price`, `product_sold`, `product_date_of_sale`) VALUES
(1, 'men\'s clothing', 'Fjallraven  Foldsack No 1 Backpack Fits 15 Laptops', 'Your perfect pack for everyday use and walks in the forest. Stash your laptop up to 15 inches in the padded sleeve your everyday', 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', 329.85, '0', '2021-11-27T20:29:54+05:30'),
(2, 'men\'s clothing', 'Mens Casual Premium Slim Fit TShirts ', 'Slimfitting style contrast raglan long sleeve threebutton henley placket light weight  soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a threebutton placket.', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 44.6, '0', '2021-10-27T20:29:54+05:30'),
(3, 'men\'s clothing', 'Mens Cotton Jacket', 'great outerwear jackets for SpringAutumnWinter suitable for many occasions such as working hiking camping mountainrock climbing cycling traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father husband or son in this thanksgiving or Christmas Day.', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', 615.89, '1', '2022-07-27T20:29:54+05:30'),
(4, 'men\'s clothing', 'Mens Casual Slim Fit', 'The color could be slightly different between on the screen and in practice.  Please note that body builds vary by person therefore detailed size information should be reviewed below on the product description.', 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 31.98, '0', '2021-10-27T20:29:54+05:30'),
(5, 'jewelery', 'John Hardy Womens Legends Naga Gold  Silver Dragon Station Chain Bracelet', 'From our Legends Collection the Naga was inspired by the mythical water dragon that protects the oceans pearl. Wear facing inward to be bestowed with love and abundance or outward for protection.', 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', 6950, '0', '2022-06-27T20:29:54+05:30'),
(6, 'jewelery', 'Solid Gold Petite Micropave ', 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', 168, '1', '2021-09-27T20:29:54+05:30'),
(7, 'jewelery', 'White Gold Plated Princess', 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement Wedding Anniversary Valentines Day...', 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', 99.9, '1', '2022-06-27T20:29:54+05:30'),
(8, 'jewelery', 'Pierced Owl Rose Gold Plated Stainless Steel Double', 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', 32.97, '0', '2021-11-27T20:29:54+05:30'),
(9, 'electronics', 'WD 2TB Elements Portable External Hard Drive  USB 30 ', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity Compatibility Formatted NTFS for Windows 10 Windows 8.1 Windows 7 Reformatting may be required for other operating systems Compatibility may vary depending on users hardware configuration and operating system', 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 704, '1', '2022-07-27T20:29:54+05:30'),
(10, 'electronics', 'SanDisk SSD PLUS 1TB Internal SSD  SATA III 6 Gbs', 'Easy upgrade for faster boot up shutdown application load and response As compared to 5400 RPM SATA 2.5 hard drive Based on published specifications and internal benchmarking tests using PCMark vantage scores Boosts burst write performance making it ideal for typical PC workloads The perfect balance of performance and reliability Readwrite speeds of up to 535MBs450MBs Based on internal testing Performance may vary depending upon drive capacity host device OS and application.', 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 763, '0', '2022-03-27T20:29:54+05:30'),
(11, 'electronics', 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 25', '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultraslim notebooks. Supports TRIM command Garbage Collection technology RAID and ECC Error Checking  Correction to provide the optimized performance and enhanced reliability.', 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', 109, '0', '2021-09-27T20:29:54+05:30'),
(12, 'electronics', 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience Play anywhere Fast and easy setup Sleek design with high capacity 3year manufacturers limited warranty', 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 798, '1', '2022-03-27T20:29:54+05:30'),
(13, 'electronics', 'Acer SB220Q bi 215 inches Full HD 1920 x 1080 IPS UltraThin', '21. 5 inches Full HD 1920 x 1080 widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate 75Hz  Using HDMI port Zeroframe design  ultrathin  4ms response time  IPS panel Aspect ratio  16 9. Color Supported  16. 7 million colors. Brightness  250 nit Tilt angle 5 degree to 15 degree. Horizontal viewing angle178 degree. Vertical viewing angle178 degree 75 hertz', 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', 4792, '0', '2022-04-27T20:29:54+05:30'),
(14, 'electronics', 'Samsung 49Inch CHG90 144Hz Curved Gaming Monitor LC49HG90DMNXZA  Super Ultrawide Screen QLED ', '49 INCH SUPER ULTRAWIDE 329 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT QLED TECHNOLOGY HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur ghosting and reduce input lag', 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', 4999.95, '1', '2022-01-27T20:29:54+05:30'),
(15, 'women\'s clothing', 'BIYLACLESEN Womens 3in1 Snowboard Jacket Winter Coats', 'NoteThe Jackets is US standard size Please choose size as your usual wear Material 100 Polyester Detachable Liner Fabric Warm Fleece. Detachable Functional Liner Skin Friendly Lightweigt and Warm.Stand Collar Liner jacket keep you warm in cold weather. Zippered Pockets 2 Zippered Hand Pockets 2 Zippered Pockets on Chest enough to keep cards or keysand 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and waterfor a comfortable fit. 3 in 1 Detachable Design provide more convenience you can separate the coat and inner as needed or wear it together. It is suitable for different season and help you adapt to different climates', 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg', 284.95, '1', '2022-01-27T20:29:54+05:30'),
(16, 'women\'s clothing', 'Lock and Love Womens Removable Hooded Faux Leather Moto Biker Jacket', '100 POLYURETHANEshell 100 POLYESTERlining 75 POLYESTER 25 COTTON SWEATER Faux leather material for style and comfort  2 pockets of front 2ForOne Hooded denim style faux leather jacket Button detail on waist  Detail stitching at sides HAND WASH ONLY  DO NOT BLEACH  LINE DRY  DO NOT IRON', 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg', 59.9, '0', '2021-10-27T20:29:54+05:30'),
(17, 'women\'s clothing', 'Rain Jacket Women Windbreaker Striped Climbing Raincoats', 'Lightweight perfet for trip or casual wearLong sleeve with hooded adjustable drawstring waist design. Button and zipper front closure raincoat fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things it covers the hips and the hood is generous but doesnt overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.', 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', 359.91, '0', '2022-05-27T20:29:54+05:30'),
(18, 'women\'s clothing', 'MBJ Womens Solid Short Sleeve Boat Neck V ', '95 RAYON 5 SPANDEX Made in USA or Imported Do Not Bleach Lightweight fabric with great stretch for comfort Ribbed on sleeves and neckline  Double stitching on bottom hem', 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg', 29.55, '1', '2021-11-27T20:29:54+05:30'),
(19, 'women\'s clothing', 'Opna Womens Short Sleeve Moisture', '100 Polyester Machine wash 100 cationic polyester interlock Machine Wash  Pre Shrunk for a Great Fit Lightweight roomy and highly breathable with moisture wicking fabric which helps to keep moisture away Soft Lightweight Fabric with comfortable Vneck collar and a slimmer fit delivers a sleek more feminine silhouette and Added Comfort', 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg', 39.75, '0', '2022-01-27T20:29:54+05:30'),
(20, 'women\'s clothing', 'DANVOUY Womens T Shirt Casual Cotton Short', '95Cotton5Spandex Features Casual Short Sleeve Letter PrintVNeckFashion Tees The fabric is soft and has some stretch. Occasion CasualOfficeBeachSchoolHomeStreet. Season SpringSummerAutumnWinter.', 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg', 77.94, '0', '2022-02-27T20:29:54+05:30'),
(21, 'men\'s clothing', 'Fjallraven  Foldsack No 1 Backpack Fits 15 Laptops', 'Your perfect pack for everyday use and walks in the forest. Stash your laptop up to 15 inches in the padded sleeve your everyday', 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', 439.8, '1', '2021-12-27T20:29:54+05:30'),
(22, 'men\'s clothing', 'Mens Casual Premium Slim Fit TShirts ', 'Slimfitting style contrast raglan long sleeve threebutton henley placket light weight  soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a threebutton placket.', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 111.5, '0', '2022-01-27T20:29:54+05:30'),
(23, 'men\'s clothing', 'Mens Cotton Jacket', 'great outerwear jackets for SpringAutumnWinter suitable for many occasions such as working hiking camping mountainrock climbing cycling traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father husband or son in this thanksgiving or Christmas Day.', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', 559.9, '0', '2022-06-27T20:29:54+05:30'),
(24, 'men\'s clothing', 'Mens Casual Slim Fit', 'The color could be slightly different between on the screen and in practice.  Please note that body builds vary by person therefore detailed size information should be reviewed below on the product description.', 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 31.98, '1', '2021-10-27T20:29:54+05:30'),
(25, 'jewelery', 'John Hardy Womens Legends Naga Gold  Silver Dragon Station Chain Bracelet', 'From our Legends Collection the Naga was inspired by the mythical water dragon that protects the oceans pearl. Wear facing inward to be bestowed with love and abundance or outward for protection.', 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', 695, '0', '2021-09-27T20:29:54+05:30'),
(26, 'jewelery', 'Solid Gold Petite Micropave ', 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', 504, '0', '2021-11-27T20:29:54+05:30'),
(27, 'jewelery', 'White Gold Plated Princess', 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement Wedding Anniversary Valentines Day...', 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', 79.92, '1', '2022-04-27T20:29:54+05:30'),
(28, 'jewelery', 'Pierced Owl Rose Gold Plated Stainless Steel Double', 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', 131.88, '1', '2022-08-27T20:29:54+05:30'),
(29, 'electronics', 'WD 2TB Elements Portable External Hard Drive  USB 30 ', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity Compatibility Formatted NTFS for Windows 10 Windows 8.1 Windows 7 Reformatting may be required for other operating systems Compatibility may vary depending on users hardware configuration and operating system', 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 640, '0', '2022-06-27T20:29:54+05:30'),
(30, 'electronics', 'SanDisk SSD PLUS 1TB Internal SSD  SATA III 6 Gbs', 'Easy upgrade for faster boot up shutdown application load and response As compared to 5400 RPM SATA 2.5 hard drive Based on published specifications and internal benchmarking tests using PCMark vantage scores Boosts burst write performance making it ideal for typical PC workloads The perfect balance of performance and reliability Readwrite speeds of up to 535MBs450MBs Based on internal testing Performance may vary depending upon drive capacity host device OS and application.', 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 218, '1', '2021-10-27T20:29:54+05:30'),
(31, 'electronics', 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 25', '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultraslim notebooks. Supports TRIM command Garbage Collection technology RAID and ECC Error Checking  Correction to provide the optimized performance and enhanced reliability.', 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', 545, '0', '2022-01-27T20:29:54+05:30'),
(32, 'electronics', 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience Play anywhere Fast and easy setup Sleek design with high capacity 3year manufacturers limited warranty', 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 1026, '0', '2022-05-27T20:29:54+05:30'),
(33, 'electronics', 'Acer SB220Q bi 215 inches Full HD 1920 x 1080 IPS UltraThin', '21. 5 inches Full HD 1920 x 1080 widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate 75Hz  Using HDMI port Zeroframe design  ultrathin  4ms response time  IPS panel Aspect ratio  16 9. Color Supported  16. 7 million colors. Brightness  250 nit Tilt angle 5 degree to 15 degree. Horizontal viewing angle178 degree. Vertical viewing angle178 degree 75 hertz', 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', 1198, '1', '2021-10-27T20:29:54+05:30'),
(34, 'electronics', 'Samsung 49Inch CHG90 144Hz Curved Gaming Monitor LC49HG90DMNXZA  Super Ultrawide Screen QLED ', '49 INCH SUPER ULTRAWIDE 329 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT QLED TECHNOLOGY HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur ghosting and reduce input lag', 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', 999.99, '0', '2021-09-27T20:29:54+05:30'),
(35, 'women\'s clothing', 'BIYLACLESEN Womens 3in1 Snowboard Jacket Winter Coats', 'NoteThe Jackets is US standard size Please choose size as your usual wear Material 100 Polyester Detachable Liner Fabric Warm Fleece. Detachable Functional Liner Skin Friendly Lightweigt and Warm.Stand Collar Liner jacket keep you warm in cold weather. Zippered Pockets 2 Zippered Hand Pockets 2 Zippered Pockets on Chest enough to keep cards or keysand 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and waterfor a comfortable fit. 3 in 1 Detachable Design provide more convenience you can separate the coat and inner as needed or wear it together. It is suitable for different season and help you adapt to different climates', 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg', 569.9, '1', '2022-06-27T20:29:54+05:30'),
(36, 'women\'s clothing', 'Lock and Love Womens Removable Hooded Faux Leather Moto Biker Jacket', '100 POLYURETHANEshell 100 POLYESTERlining 75 POLYESTER 25 COTTON SWEATER Faux leather material for style and comfort  2 pockets of front 2ForOne Hooded denim style faux leather jacket Button detail on waist  Detail stitching at sides HAND WASH ONLY  DO NOT BLEACH  LINE DRY  DO NOT IRON', 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg', 269.55, '1', '2022-05-27T20:29:54+05:30'),
(37, 'women\'s clothing', 'Rain Jacket Women Windbreaker Striped Climbing Raincoats', 'Lightweight perfet for trip or casual wearLong sleeve with hooded adjustable drawstring waist design. Button and zipper front closure raincoat fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things it covers the hips and the hood is generous but doesnt overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.', 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', 279.93, '0', '2022-03-27T20:29:54+05:30'),
(38, 'women\'s clothing', 'MBJ Womens Solid Short Sleeve Boat Neck V ', '95 RAYON 5 SPANDEX Made in USA or Imported Do Not Bleach Lightweight fabric with great stretch for comfort Ribbed on sleeves and neckline  Double stitching on bottom hem', 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg', 29.55, '0', '2021-11-27T20:29:54+05:30'),
(39, 'women\'s clothing', 'Opna Womens Short Sleeve Moisture', '100 Polyester Machine wash 100 cationic polyester interlock Machine Wash  Pre Shrunk for a Great Fit Lightweight roomy and highly breathable with moisture wicking fabric which helps to keep moisture away Soft Lightweight Fabric with comfortable Vneck collar and a slimmer fit delivers a sleek more feminine silhouette and Added Comfort', 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg', 79.5, '1', '2022-06-27T20:29:54+05:30'),
(40, 'women\'s clothing', 'DANVOUY Womens T Shirt Casual Cotton Short', '95Cotton5Spandex Features Casual Short Sleeve Letter PrintVNeckFashion Tees The fabric is soft and has some stretch. Occasion CasualOfficeBeachSchoolHomeStreet. Season SpringSummerAutumnWinter.', 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg', 129.9, '0', '2022-06-27T20:29:54+05:30'),
(41, 'men\'s clothing', 'Fjallraven  Foldsack No 1 Backpack Fits 15 Laptops', 'Your perfect pack for everyday use and walks in the forest. Stash your laptop up to 15 inches in the padded sleeve your everyday', 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg', 549.75, '0', '2022-01-27T20:29:54+05:30'),
(42, 'men\'s clothing', 'Mens Casual Premium Slim Fit TShirts ', 'Slimfitting style contrast raglan long sleeve threebutton henley placket light weight  soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a threebutton placket.', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 89.2, '1', '2021-12-27T20:29:54+05:30'),
(43, 'men\'s clothing', 'Mens Cotton Jacket', 'great outerwear jackets for SpringAutumnWinter suitable for many occasions such as working hiking camping mountainrock climbing cycling traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father husband or son in this thanksgiving or Christmas Day.', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', 503.91, '0', '2022-05-27T20:29:54+05:30'),
(44, 'men\'s clothing', 'Mens Casual Slim Fit', 'The color could be slightly different between on the screen and in practice.  Please note that body builds vary by person therefore detailed size information should be reviewed below on the product description.', 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 63.96, '0', '2021-12-27T20:29:54+05:30'),
(45, 'jewelery', 'John Hardy Womens Legends Naga Gold  Silver Dragon Station Chain Bracelet', 'From our Legends Collection the Naga was inspired by the mythical water dragon that protects the oceans pearl. Wear facing inward to be bestowed with love and abundance or outward for protection.', 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg', 6950, '1', '2022-06-27T20:29:54+05:30'),
(46, 'jewelery', 'Solid Gold Petite Micropave ', 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', 1512, '0', '2022-05-27T20:29:54+05:30'),
(47, 'jewelery', 'White Gold Plated Princess', 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement Wedding Anniversary Valentines Day...', 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', 109.89, '0', '2022-07-27T20:29:54+05:30'),
(48, 'jewelery', 'Pierced Owl Rose Gold Plated Stainless Steel Double', 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', 87.92, '1', '2022-04-27T20:29:54+05:30'),
(49, 'electronics', 'WD 2TB Elements Portable External Hard Drive  USB 30 ', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity Compatibility Formatted NTFS for Windows 10 Windows 8.1 Windows 7 Reformatting may be required for other operating systems Compatibility may vary depending on users hardware configuration and operating system', 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 768, '1', '2022-08-27T20:29:54+05:30'),
(50, 'electronics', 'SanDisk SSD PLUS 1TB Internal SSD  SATA III 6 Gbs', 'Easy upgrade for faster boot up shutdown application load and response As compared to 5400 RPM SATA 2.5 hard drive Based on published specifications and internal benchmarking tests using PCMark vantage scores Boosts burst write performance making it ideal for typical PC workloads The perfect balance of performance and reliability Readwrite speeds of up to 535MBs450MBs Based on internal testing Performance may vary depending upon drive capacity host device OS and application.', 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 1090, '0', '2022-06-27T20:29:54+05:30'),
(51, 'electronics', 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 25', '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultraslim notebooks. Supports TRIM command Garbage Collection technology RAID and ECC Error Checking  Correction to provide the optimized performance and enhanced reliability.', 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', 981, '1', '2022-05-27T20:29:54+05:30'),
(52, 'electronics', 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience Play anywhere Fast and easy setup Sleek design with high capacity 3year manufacturers limited warranty', 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 1254, '0', '2022-07-27T20:29:54+05:30'),
(53, 'electronics', 'Acer SB220Q bi 215 inches Full HD 1920 x 1080 IPS UltraThin', '21. 5 inches Full HD 1920 x 1080 widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate 75Hz  Using HDMI port Zeroframe design  ultrathin  4ms response time  IPS panel Aspect ratio  16 9. Color Supported  16. 7 million colors. Brightness  250 nit Tilt angle 5 degree to 15 degree. Horizontal viewing angle178 degree. Vertical viewing angle178 degree 75 hertz', 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', 6589, '0', '2022-07-27T20:29:54+05:30'),
(54, 'electronics', 'Samsung 49Inch CHG90 144Hz Curved Gaming Monitor LC49HG90DMNXZA  Super Ultrawide Screen QLED ', '49 INCH SUPER ULTRAWIDE 329 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT QLED TECHNOLOGY HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur ghosting and reduce input lag', 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', 999.99, '1', '2021-09-27T20:29:54+05:30'),
(55, 'women\'s clothing', 'BIYLACLESEN Womens 3in1 Snowboard Jacket Winter Coats', 'NoteThe Jackets is US standard size Please choose size as your usual wear Material 100 Polyester Detachable Liner Fabric Warm Fleece. Detachable Functional Liner Skin Friendly Lightweigt and Warm.Stand Collar Liner jacket keep you warm in cold weather. Zippered Pockets 2 Zippered Hand Pockets 2 Zippered Pockets on Chest enough to keep cards or keysand 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and waterfor a comfortable fit. 3 in 1 Detachable Design provide more convenience you can separate the coat and inner as needed or wear it together. It is suitable for different season and help you adapt to different climates', 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg', 626.89, '0', '2022-07-27T20:29:54+05:30'),
(56, 'women\'s clothing', 'Lock and Love Womens Removable Hooded Faux Leather Moto Biker Jacket', '100 POLYURETHANEshell 100 POLYESTERlining 75 POLYESTER 25 COTTON SWEATER Faux leather material for style and comfort  2 pockets of front 2ForOne Hooded denim style faux leather jacket Button detail on waist  Detail stitching at sides HAND WASH ONLY  DO NOT BLEACH  LINE DRY  DO NOT IRON', 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg', 179.7, '1', '2022-02-27T20:29:54+05:30'),
(57, 'women\'s clothing', 'Rain Jacket Women Windbreaker Striped Climbing Raincoats', 'Lightweight perfet for trip or casual wearLong sleeve with hooded adjustable drawstring waist design. Button and zipper front closure raincoat fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things it covers the hips and the hood is generous but doesnt overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.', 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', 339.99, '1', '2021-09-27T20:29:54+05:30'),
(58, 'women\'s clothing', 'MBJ Womens Solid Short Sleeve Boat Neck V ', '95 RAYON 5 SPANDEX Made in USA or Imported Do Not Bleach Lightweight fabric with great stretch for comfort Ribbed on sleeves and neckline  Double stitching on bottom hem', 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg', 59.1, '0', '2022-02-27T20:29:54+05:30'),
(59, 'women\'s clothing', 'Opna Womens Short Sleeve Moisture', '100 Polyester Machine wash 100 cationic polyester interlock Machine Wash  Pre Shrunk for a Great Fit Lightweight roomy and highly breathable with moisture wicking fabric which helps to keep moisture away Soft Lightweight Fabric with comfortable Vneck collar and a slimmer fit delivers a sleek more feminine silhouette and Added Comfort', 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg', 79.5, '0', '2022-06-27T20:29:54+05:30'),
(60, 'women\'s clothing', 'DANVOUY Womens T Shirt Casual Cotton Short', '95Cotton5Spandex Features Casual Short Sleeve Letter PrintVNeckFashion Tees The fabric is soft and has some stretch. Occasion CasualOfficeBeachSchoolHomeStreet. Season SpringSummerAutumnWinter.', 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg', 412.99, '1', '2021-09-27T20:29:54+05:30');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `product_id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
